### model
model_name_or_path: /data/zzh/Qwen2.5-14B-Instruct
quantization_bit: 4
trust_remote_code: false

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: entity_trans_de
template: qwen
cutoff_len: 2048
#max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen-14b-de-e50/lora/sft
logging_steps: 200
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 50.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
#ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: epoch
#eval_strategy: steps
#eval_steps: 500